# Generated by Django 3.0.4 on 2020-09-24 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ofp_plan_date', models.DateField()),
                ('f_in_date', models.DateField()),
                ('f_out_date', models.DateField()),
                ('invoice', models.CharField(max_length=100)),
                ('t_qty', models.IntegerField()),
                ('a_qty', models.IntegerField()),
                ('a_part', models.CharField(max_length=100)),
                ('rfid_seal', models.CharField(max_length=100)),
                ('container_no', models.CharField(max_length=100)),
                ('seal_no', models.IntegerField()),
                ('lr_no', models.IntegerField()),
                ('vehicle_no', models.CharField(max_length=100)),
                ('s_line', models.CharField(max_length=100)),
                ('clearance', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('port', models.CharField(max_length=100)),
                ('f_dest', models.CharField(max_length=100)),
                ('product', models.CharField(max_length=100)),
                ('booking_no', models.IntegerField()),
                ('transporter', models.CharField(max_length=100)),
                ('cont_size', models.CharField(max_length=100)),
                ('detn_days', models.IntegerField()),
                ('detain_reason', models.CharField(max_length=100)),
                ('mobile_no', models.IntegerField()),
                ('remarks', models.CharField(max_length=100)),
            ],
        ),
    ]
