# Generated by Django 3.0.4 on 2020-09-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collect', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='a_part',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='a_qty',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='booking_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='clearance',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='cont_size',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='container_no',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='destination',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='detain_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='detn_days',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='f_dest',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='f_in_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='f_out_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='invoice',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='lr_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='mobile_no',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='ofp_plan_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='port',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='product',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='remarks',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='rfid_seal',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='s_line',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='seal_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='t_qty',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='transporter',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='vehicle_no',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
